spring.application.name=ollama-embed
spring.ai.ollama.embedding.model=embeddinggemma
spring.ai.ollama.chat.model=gemma3


spring.datasource.url=jdbc:postgresql://localhost:5432/<db-username>
spring.datasource.username=<db-username>
spring.datasource.password=<db-password>
spring.ai.vectorstore.pgvector.tableName=vector_store
spring.ai.vectorstore.pgvector.dimension=768
spring.ai.vectorstore.pgvector.createTable=true
spring.ai.vectorstore.pgvector.createIndex=true

spring.liquibase.enabled=true
spring.liquibase.change-log= classpath:db/changelog/changelog-master.yaml

